---
driver:
  name: vagrant

provisioner:
  name: chef_zero

  use - provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[web::default]
      - recipe[nodejs::nodejs]
      - recipe[web::npm_packages]
      # - recipe[web::clone_repo]
    attributes: