name             'web'
maintainer       'Sai Ongole'
maintainer_email 'svo214@nyu.edu'
license          'No rights reserved'
description      'Installs/Configures web'
long_description 'Installs/Configures web'
version          '0.1.0'
